# Generated by Django 4.2.2 on 2023-08-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls_feed',
            name='status',
            field=models.TextField(default=None),
        ),
    ]
