# Generated by Django 4.2.2 on 2023-08-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_alerts', '0003_alter_urls_feed_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls_feed',
            name='status',
        ),
    ]
