# Generated by Django 4.2.2 on 2023-08-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_alerts', '0004_remove_urls_feed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls_feed',
            name='status',
            field=models.TextField(default=None, null=True),
        ),
    ]
